language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coveralls
env:
  matrix:
    - INTEGRATION_TARGET=
    - INTEGRATION_TARGET=fec
    - INTEGRATION_TARGET=atf
    - INTEGRATION_TARGET=epa
    - INTEGRATION_TARGET=uspto
script:
  - ./test-travis.sh
after_success:
  - if [[ $INTEGRATION_TARGET = '' ]] && [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then coveralls; fi
