language: python
sudo: false
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - pip install coveralls
script:
    - nosetests --with-cov --cov-report term-missing --cov regparser tests/*.py
    - flake8 .
after_success:
    coveralls
